name: "tagged-release"

on:
  push:
    tags:
      - "v*"
 
jobs:
  build:
    strategy:
      matrix:
        dotnet-version: [6.0.x, 7.0.x, 8.0.x]
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 🚀 Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -r linux-x64 -c Release

  release:
    name: "Release"
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -r linux-x64 -c Release
    - name: "GH Release"
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        zip ./version2-dll.zip ./Version2/bin/Release/netstandard2.0/publish/Version2.dll
        gh release create $TAG ./version2-dll.zip --notes $TAG
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
      shell: bash
